Repository ZupIT/ritchie-formulas, pull requests merged in 2020-05, with the labels that each got.

#26 Feature/coffee multlang
  .gitignore
  Makefile
  aws/terraform/src/Makefile
  copy-bin-configs.sh
  docker/compose/src/Makefile
  github/fast-merge/src/Makefile
  github/navigate-handbook/src/Makefile
  github/search-handbook/src/Makefile
  kafka/src/Makefile
  kubernetes/core/src/Makefile
  scaffold/coffee-go/src/Makefile
  scaffold/coffee-java/README.md
  scaffold/coffee-java/config.json
  scaffold/coffee-java/src/Main.java
  scaffold/coffee-java/src/Makefile
  scaffold/coffee-java/src/coffee/Coffee.java
  scaffold/coffee-java/src/run_template
  scaffold/coffee-node/README.md
  scaffold/coffee-node/config.json
  scaffold/coffee-node/src/Makefile
  scaffold/coffee-node/src/coffee/coffee.js
  scaffold/coffee-node/src/index.js
  scaffold/coffee-node/src/package.json
  scaffold/coffee-node/src/run_template
  scaffold/coffee-python/README.md
  scaffold/coffee-python/config.json
  scaffold/coffee-python/src/Makefile
  scaffold/coffee-python/src/coffee/coffee.py
  scaffold/coffee-python/src/main.py
  scaffold/coffee-shell/README.md
  scaffold/coffee-shell/config.json
  scaffold/coffee-shell/src/Makefile
  scaffold/coffee-shell/src/coffee/coffee.sh
  scaffold/coffee-shell/src/main.sh
  scaffold/spring-starter/src/Makefile
  tree/tree.json
Labels: feature

#27 [FIX] updating gitbook urls
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: bug, documentation

#21 Feature/code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, feature
