Repository ZupIT/ritchie-formulas, pull requests merged in 2020-08, with the labels that each got.

#110 change readme and contributing
  CONTRIBUTING.md
  README.md
Labels: 2.0.0, documentation

#107 [Improvement] Github Update Fork - V2
  github/update/fork/config.json
  github/update/fork/src/fork/fork.sh
  github/update/fork/src/main.sh
Labels: 2.0.0

#106 [Improvement] Github Update Fork - V1
  github/update/fork/config.json
  github/update/fork/src/fork/fork.sh
  github/update/fork/src/main.sh
Labels: 1.0.0

#119 [FORMULA] RIT DEMO HELLO-WORLD
  CODEOWNERS
  demo/hello-world/Dockerfile
  demo/hello-world/Makefile
  demo/hello-world/README.md
  demo/hello-world/build.bat
  demo/hello-world/config.json
  demo/hello-world/help.json
  demo/hello-world/help.txt
  demo/hello-world/metadata.json
  demo/hello-world/set_umask.sh
  demo/hello-world/src/go.mod
  demo/hello-world/src/main.go
  demo/hello-world/src/pkg/hello/hello.go
  demo/hello-world/src/pkg/hello/hello_test.go
  demo/help.json
  github/update/fork/config.json
  github/update/fork/src/fork/fork.sh
  github/update/fork/src/main.sh
Labels: 2.0.0, documentation

#122 [FEATURE] Update stdin on formula README
  CODEOWNERS
  demo/hello-world/README.md
Labels: 2.0.0, documentation

#128 [FORMULA] RIT GITHUB PUBLISH REPO
  github/publish/help.json
  github/publish/repo/Dockerfile
  github/publish/repo/Makefile
  github/publish/repo/README.md
  github/publish/repo/config.json
  github/publish/repo/docs/img/repo-published-on-github.png
  github/publish/repo/docs/img/rit-list-repo.png
  github/publish/repo/help.json
  github/publish/repo/help.txt
  github/publish/repo/metadata.json
  github/publish/repo/set_umask.sh
  github/publish/repo/src/formula/formula.sh
  github/publish/repo/src/main.sh
Labels: 2.0.0

#135 [ENHANCEMENT] Github publish formula files
  .github/PULL_REQUEST_TEMPLATE.md
  github/publish/repo/README.md
  github/publish/repo/config.json
  github/publish/repo/help.txt
  github/publish/repo/src/formula/formula.sh
Labels: 2.0.0, enhancement

#141 [FIX] Rename Java Test File
  templates/create_formula/languages/java/src/test/java/com/ritchie/formula/FormulaTest.java
Labels: bug

#109 Formula yourls
  Makefile
  tree/tree.json
  yourls/init/config.json
  yourls/init/src/Dockerfile
  yourls/init/src/Makefile
  yourls/init/src/init/init.sh
  yourls/init/src/main.sh
  yourls/init/src/set_umask.sh
  yourls/shorturl/config.json
  yourls/shorturl/lib/json-simple-1.1.1.jar
  yourls/shorturl/manifest.txt
  yourls/shorturl/src/Dockerfile
  yourls/shorturl/src/Main.java
  yourls/shorturl/src/Makefile
  yourls/shorturl/src/TestMain.java
  yourls/shorturl/src/run_template
  yourls/shorturl/src/set_umask.sh
  yourls/shorturl/src/shorturl/Shorturl.java
Labels: 1.0.0

#148 [ENHANCEMENT] - RIT GITHUB PUBLISH REPO
  github/publish/repo/config.json
  github/publish/repo/src/formula/formula.sh
Labels: 2.0.0, enhancement

#155 [FEATURE] COFFEE FORMULAS TO "DEMO" GROUP
  demo/coffee-go/Dockerfile
  demo/coffee-go/Makefile
  demo/coffee-go/README.md
  demo/coffee-go/build.bat
  demo/coffee-go/config.json
  demo/coffee-go/help.json
  demo/coffee-go/metadata.json
  demo/coffee-go/set_umask.sh
  demo/coffee-go/src/go.mod
  demo/coffee-go/src/main.go
  demo/coffee-go/src/pkg/coffee/coffee.go
  demo/coffee-go/src/pkg/coffee/coffee_test.go
  demo/coffee-java/Dockerfile
  demo/coffee-java/Makefile
  demo/coffee-java/README.md
  demo/coffee-java/build.bat
  demo/coffee-java/config.json
  demo/coffee-java/help.json
  demo/coffee-java/metadata.json
  demo/coffee-java/pom.xml
  demo/coffee-java/set_umask.sh
  demo/coffee-java/src/main/java/Main.java
  demo/coffee-java/src/main/java/coffee/Coffee.java
  demo/coffee-node/Dockerfile
  demo/coffee-node/Makefile
  demo/coffee-node/README.md
  demo/coffee-node/build.bat
  demo/coffee-node/config.json
  demo/coffee-node/help.json
  demo/coffee-node/metadata.json
  demo/coffee-node/set_umask.sh
  demo/coffee-node/src/coffee/coffee.js
  demo/coffee-node/src/main.js
  demo/coffee-node/src/package.json
  demo/coffee-python/Dockerfile
  demo/coffee-python/Makefile
  demo/coffee-python/README.md
  demo/coffee-python/build.bat
  demo/coffee-python/config.json
  demo/coffee-python/help.json
  demo/coffee-python/metadata.json
  demo/coffee-python/set_umask.sh
  demo/coffee-python/src/coffee/coffee.py
  demo/coffee-python/src/main.py
  demo/coffee-shell/Dockerfile
  demo/coffee-shell/Makefile
  demo/coffee-shell/README.md
  demo/coffee-shell/config.json
  demo/coffee-shell/help.json
  demo/coffee-shell/metadata.json
  demo/coffee-shell/set_umask.sh
  demo/coffee-shell/src/coffee/coffee.sh
  demo/coffee-shell/src/main.sh
  scaffold/generate/coffee-go/README.md
  scaffold/generate/coffee-java/README.md
  scaffold/generate/coffee-node/README.md
  scaffold/generate/coffee-python/README.md
  scaffold/generate/coffee-shell/README.md
Labels: 2.0.0, enhancement

#160 [FEATURE] UPDATE HELLO WORLD TEMPLATE (GOLANG)
  templates/create_formula/languages/go/README.md
  templates/create_formula/languages/go/config.json
  templates/create_formula/languages/go/src/main.go
  templates/create_formula/languages/go/src/pkg/formula/formula.go
  templates/create_formula/languages/go/src/pkg/formula/formula_test.go
Labels: 2.0.0, enhancement, feature

#162 [DOC] Fix broken URL
  README.md
Labels: documentation

#159 Feature/template ruby
  templates/create_formula/languages/ruby/Dockerfile
  templates/create_formula/languages/ruby/Makefile
  templates/create_formula/languages/ruby/README.md
  templates/create_formula/languages/ruby/build.bat
  templates/create_formula/languages/ruby/config.json
  templates/create_formula/languages/ruby/metadata.json
  templates/create_formula/languages/ruby/set_umask.sh
  templates/create_formula/languages/ruby/src/Gemfile
  templates/create_formula/languages/ruby/src/formula/formula.rb
  templates/create_formula/languages/ruby/src/index.rb
Labels: 2.0.0, enhancement, feature
