Repository ZupIT/ritchie-formulas, pull requests merged in 2020-12, with the labels that each got.

#328 [#32362] New Template (Terraform)
  templates/create_formula/languages/terraform/Dockerfile
  templates/create_formula/languages/terraform/Makefile
  templates/create_formula/languages/terraform/README.md
  templates/create_formula/languages/terraform/build.bat
  templates/create_formula/languages/terraform/config.json
  templates/create_formula/languages/terraform/metadata.json
  templates/create_formula/languages/terraform/set_umask.sh
  templates/create_formula/languages/terraform/src/main.bat
  templates/create_formula/languages/terraform/src/main.sh
  templates/create_formula/languages/terraform/src/tf-files/main.tf
  templates/create_formula/languages/terraform/src/tf-files/variables.tf
  templates/create_formula/languages/terraform/src/unix/formula/formula.sh
Labels: feature

#329 Fix/template repo readme
  templates/create_formula/root/README.md
Labels: enhancement

#326 Fix/rit publish repo formula (stdin to input flag)
  publish/repo/src/unix/formula/formula.sh
  publish/repo/src/windows/formula/formula.bat
Labels: WIP, enhancement

#325 Fix/Gitlab publish formula "branch"
  gitlab/publish/repo/src/unix/formula/formula.sh
Labels: WIP, enhancement

#323 [#35704] feature/new build files
  templates/create_formula/languages/csharp/Makefile
  templates/create_formula/languages/csharp/build.sh
  templates/create_formula/languages/go/Makefile
  templates/create_formula/languages/go/build.sh
  templates/create_formula/languages/java11/Makefile
  templates/create_formula/languages/java11/build.sh
  templates/create_formula/languages/java8/Makefile
  templates/create_formula/languages/java8/build.sh
  templates/create_formula/languages/node/Makefile
  templates/create_formula/languages/node/build.sh
  templates/create_formula/languages/php/Makefile
  templates/create_formula/languages/php/build.sh
  templates/create_formula/languages/powershell/Makefile
  templates/create_formula/languages/powershell/build.sh
  templates/create_formula/languages/python3/Makefile
  templates/create_formula/languages/python3/build.sh
  templates/create_formula/languages/ruby/Makefile
  templates/create_formula/languages/ruby/build.sh
  templates/create_formula/languages/ruby/src/formula/formula.rb
  templates/create_formula/languages/ruby/src/index.rb
  templates/create_formula/languages/rust/Makefile
  templates/create_formula/languages/rust/build.sh
  templates/create_formula/languages/shell-bat/Makefile
  templates/create_formula/languages/shell-bat/build.sh
  templates/create_formula/languages/typescript/Makefile
  templates/create_formula/languages/typescript/build.sh
Labels: feature, 👁 under-review
