Repository ZupIT/ritchie-formulas, pull requests merged in 2020-07, with the labels that each got.

#59 [Feature] - Formula Git Update Fork
  Makefile
  github/update/fork/config.json
  github/update/fork/src/Dockerfile
  github/update/fork/src/Makefile
  github/update/fork/src/fork/fork.sh
  github/update/fork/src/main.sh
  github/update/fork/src/set_umask.sh
  tree/tree.json
Labels: feature

#67 Machine learning template formula
  Makefile
  jupyter/machine_learning/template/README.md
  jupyter/machine_learning/template/config.json
  jupyter/machine_learning/template/src/Dockerfile
  jupyter/machine_learning/template/src/Makefile
  jupyter/machine_learning/template/src/main.py
  jupyter/machine_learning/template/src/set_umask.sh
  jupyter/machine_learning/template/src/template/assets/ritchie_logo.png
  jupyter/machine_learning/template/src/template/notebook_template.py
  jupyter/machine_learning/template/src/template/template.py
  tree/tree.json
Labels: feature

#101 change readme of create formula
  templates/create_formula/README.md
Labels: 2.0.0, documentation

#108 Remove shell from makefiles
  aws/add/terraform-eks/Makefile
  aws/add/terraform-eks/build.bat
  aws/add/terraform-vpc/Makefile
  aws/add/terraform-vpc/build.bat
  aws/apply/terraform/Makefile
  aws/apply/terraform/build.bat
  aws/apply/terraform/src/main.go
  aws/create/bucket/Makefile
  aws/create/bucket/build.bat
  aws/delete/bucket/Makefile
  aws/delete/bucket/build.bat
  aws/generate/terraform-project/Makefile
  aws/generate/terraform-project/build.bat
  aws/list/bucket/Makefile
  aws/list/bucket/build.bat
  circleci/add/env/Makefile
  circleci/add/env/build.bat
  docker/generate/compose/Makefile
  docker/generate/compose/build.bat
  github/merge/branch/Makefile
  github/merge/branch/build.bat
  github/merge/branch/src/main.go
  github/navigate/handbook/Makefile
  github/navigate/handbook/build.bat
  github/search/handbook/Makefile
  github/search/handbook/build.bat
  kafka/consume/message/Makefile
  kafka/consume/message/build.bat
  kafka/create/topic/Makefile
  kafka/create/topic/build.bat
  kafka/list/topic/Makefile
  kafka/list/topic/build.bat
  kafka/produce/message/Makefile
  kafka/produce/message/build.bat
  kubernetes/create/port-forward/Makefile
  kubernetes/create/port-forward/build.bat
  kubernetes/show/health-status/Makefile
  kubernetes/show/health-status/build.bat
  kubernetes/show/logs/Makefile
  kubernetes/show/logs/build.bat
  scaffold/generate/coffee-go/Makefile
  scaffold/generate/coffee-go/build.bat
  scaffold/generate/coffee-java/build.bat
  scaffold/generate/spring-starter/Makefile
  scaffold/generate/spring-starter/build.bat
  scaffold/show/spring-starter-dependencies/Makefile
  scaffold/show/spring-starter-dependencies/build.bat
  templates/create_formula/languages/go/Makefile
  templates/create_formula/languages/go/build.bat
  templates/create_formula/languages/java/build.bat
Labels: 2.0.0
