Repository ZupIT/ritchie-formulas, pull requests merged in 2020-09, with the labels that each got.

#168 [#843] Ruby Build to Windows
  templates/create_formula/languages/ruby/build.bat
Labels: feature

#174 Template PowerShell
  templates/create_formula/languages/powershell/Dockerfile
  templates/create_formula/languages/powershell/Makefile
  templates/create_formula/languages/powershell/README.md
  templates/create_formula/languages/powershell/config.json
  templates/create_formula/languages/powershell/metadata.json
  templates/create_formula/languages/powershell/set_umask.sh
  templates/create_formula/languages/powershell/src/formula/formula.ps1
  templates/create_formula/languages/powershell/src/main.ps1
Labels: WIP

#236 [FEATURE] Preparing for Hacktoberfest
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: Hacktoberfest, documentation
