Repository ZupIT/ritchie-formulas, pull requests merged in 2020-10, with the labels that each got.

#246 [7639#] Homologate Powershell Template
  templates/create_formula/languages/powershell/Makefile
  templates/create_formula/languages/powershell/build.bat
  templates/create_formula/languages/powershell/src/main.ps1
Labels: enhancement, feature

#250 Update Rust template to match hello-world formula
  templates/create_formula/languages/rust/README.md
  templates/create_formula/languages/rust/config.json
  templates/create_formula/languages/rust/src/src/formula/mod.rs
  templates/create_formula/languages/rust/src/src/main.rs
Labels: Hacktoberfest

#253 Add tutorial field to config.json files
  aws/add/terraform-eks/config.json
  aws/add/terraform-vpc/config.json
  aws/apply/terraform/config.json
  aws/clean/bucket/config.json
  aws/create/bucket/config.json
  aws/delete/bucket/config.json
  aws/generate/terraform-project/config.json
  aws/list/bucket/config.json
  aws/set/context/config.json
  aws/update/kubeconfig/config.json
  bitbucket/create/repo/config.json
  bitbucket/delete/repo/config.json
  circleci/add/env/config.json
  circleci/follow/project/config.json
  git/update/fork/config.json
  github/add/collaborator/config.json
  github/create/repo/config.json
  github/delete/repo/config.json
  github/merge/branch/config.json
  github/publish/repo/config.json
  gitlab/create/repo/config.json
  gitlab/delete/repo/config.json
  gitlab/publish/repo/config.json
  istio/init/config.json
  jupyter/create/ml_template/config.json
  kafka/consume/message/config.json
  kafka/create/topic/config.json
  kafka/list/topic/config.json
  kafka/produce/message/config.json
  kubernetes/create/port-forward/config.json
  kubernetes/show/health-status/config.json
  kubernetes/show/logs/config.json
  publish/repo/config.json
  scaffold/generate/spring-starter/config.json
  templates/create_formula/languages/csharp/config.json
  templates/create_formula/languages/go/config.json
  templates/create_formula/languages/java11/config.json
  templates/create_formula/languages/java8/config.json
  templates/create_formula/languages/node/config.json
  templates/create_formula/languages/php/config.json
  templates/create_formula/languages/powershell/config.json
  templates/create_formula/languages/python3/config.json
  templates/create_formula/languages/ruby/config.json
  templates/create_formula/languages/rust/config.json
  templates/create_formula/languages/shell/config.json
Labels: Hacktoberfest, enhancement, good first issue

#254 Feature/language typescript
  templates/create_formula/languages/typescript/Dockerfile
  templates/create_formula/languages/typescript/Makefile
  templates/create_formula/languages/typescript/README.md
  templates/create_formula/languages/typescript/build.bat
  templates/create_formula/languages/typescript/config.json
  templates/create_formula/languages/typescript/metadata.json
  templates/create_formula/languages/typescript/set_umask.sh
  templates/create_formula/languages/typescript/src/formula/Formula.ts
  templates/create_formula/languages/typescript/src/index.ts
  templates/create_formula/languages/typescript/src/package.json
  templates/create_formula/languages/typescript/src/tsconfig.json
Labels: Hacktoberfest

#261 added required field to config json files
  templates/create_formula/languages/csharp/config.json
  templates/create_formula/languages/go/config.json
  templates/create_formula/languages/java11/config.json
  templates/create_formula/languages/java8/config.json
  templates/create_formula/languages/node/config.json
  templates/create_formula/languages/php/config.json
  templates/create_formula/languages/powershell/config.json
  templates/create_formula/languages/python3/config.json
  templates/create_formula/languages/ruby/config.json
  templates/create_formula/languages/rust/config.json
  templates/create_formula/languages/shell/config.json
  templates/create_formula/languages/typescript/config.json
Labels: Hacktoberfest, hacktoberfest-accepted

#265 Add README.md of kubernetes show logs command (#226)
  kubernetes/show/logs/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#267 Again update files with dco
  templates/create_formula/languages/node/config.json
  templates/create_formula/languages/node/src/formula/formula.js
  templates/create_formula/languages/node/src/index.js
Labels: hacktoberfest-accepted

#268 Update/java8 template
  templates/create_formula/languages/java8/config.json
  templates/create_formula/languages/java8/pom.xml
  templates/create_formula/languages/java8/src/main/java/com/ritchie/Main.java
  templates/create_formula/languages/java8/src/main/java/com/ritchie/formula/Formula.java
  templates/create_formula/languages/java8/src/test/java/com/ritchie/formula/FormulaTest.java
Labels: Hacktoberfest, hacktoberfest-accepted

#269 feature/csharp demo template
  templates/create_formula/languages/csharp/config.json
  templates/create_formula/languages/csharp/src/formula/formula.cs
  templates/create_formula/languages/csharp/src/main.cs
Labels: Hacktoberfest

#270 [895#] fix/template csharp
  templates/create_formula/languages/csharp/Makefile
  templates/create_formula/languages/csharp/src/main.cs
Labels: bug

#271 Update RIT SCAFFOLD GENERATE SPRING-STARTER formula README
  scaffold/generate/spring-starter/README.md
  scaffold/generate/spring-starter/demo.gif
Labels: Hacktoberfest, hacktoberfest-accepted

#272 Update RIT AWS APPLY TERRAFORM formula README (#196)
  aws/apply/terraform/README.md
  aws/apply/terraform/config.json
Labels: Hacktoberfest, hacktoberfest-accepted

#278 Add Readme of rit kubernetes show health-status
  kubernetes/show/health-status/README.md
Labels: Hacktoberfest

#279 Update RIT GITHUB SEARCH HANDBOOK formula README
  github/search/handbook/README.md
  github/search/handbook/demo.gif
Labels: hacktoberfest-accepted

#280 AWS APPLY TERRAFORM Docker implementation
  aws/apply/terraform/Dockerfile
  aws/apply/terraform/Makefile
  aws/apply/terraform/README.md
  aws/apply/terraform/metadata.json
Labels: Hacktoberfest

#282 [Feature] Formulas for http performance test: http-load & http-config
  http/generate/help.json
  http/generate/http-config/Dockerfile
  http/generate/http-config/Makefile
  http/generate/http-config/README.md
  http/generate/http-config/build.bat
  http/generate/http-config/config.json
  http/generate/http-config/help.json
  http/generate/http-config/metadata.json
  http/generate/http-config/set_umask.sh
  http/generate/http-config/src/go.mod
  http/generate/http-config/src/main.go
  http/generate/http-config/src/pkg/template/template.go
  http/help.json
  http/perform/help.json
  http/perform/load-test/Dockerfile
  http/perform/load-test/Makefile
  http/perform/load-test/README.md
  http/perform/load-test/build.bat
  http/perform/load-test/config.json
  http/perform/load-test/help.json
  http/perform/load-test/metadata.json
  http/perform/load-test/set_umask.sh
  http/perform/load-test/src/go.mod
  http/perform/load-test/src/main.go
  http/perform/load-test/src/pkg/ritman/histogram.go
  http/perform/load-test/src/pkg/ritman/ritman.go
  http/perform/load-test/src/pkg/ritman/target.go
Labels: Hacktoberfest, hacktoberfest-accepted

#283 Update RIT SCAFFOLD SHOW SPRING-STARTER-DEPENDENCIES formula README
  scaffold/show/spring-starter-dependencies/README.md
  scaffold/show/spring-starter-dependencies/demo.gif
Labels: hacktoberfest-accepted

#284 update java11 template
  templates/create_formula/languages/java11/config.json
  templates/create_formula/languages/java11/pom.xml
  templates/create_formula/languages/java11/src/main/java/com/ritchie/Main.java
  templates/create_formula/languages/java11/src/main/java/com/ritchie/formula/Formula.java
  templates/create_formula/languages/java11/src/test/java/com/ritchie/formula/FormulaTest.java
Labels: hacktoberfest-accepted

#285 update rit aws list bucket formula readme
  aws/list/bucket/README.md
  aws/list/bucket/demo.gif
Labels: hacktoberfest-accepted

#294 update rit github navigate handbook readme
  github/navigate/handbook/README.md
  github/navigate/handbook/demo.gif
Labels: Hacktoberfest, hacktoberfest-accepted

#299 template fix with variable password and change text
  templates/create_formula/languages/php/config.json
  templates/create_formula/languages/php/src/formula/formula.php
  templates/create_formula/languages/php/src/index.php
Labels: Hacktoberfest, hacktoberfest-accepted

#301 Update POWERSHELL Hello World template
  templates/create_formula/languages/powershell/config.json
  templates/create_formula/languages/powershell/src/formula/formula.ps1
Labels: Hacktoberfest, hacktoberfest-accepted

#302 Update RUBY Hello World template
  templates/create_formula/languages/ruby/config.json
  templates/create_formula/languages/ruby/src/formula/formula.rb
  templates/create_formula/languages/ruby/src/index.rb
Labels: hacktoberfest-accepted

#304 Update the README AWS create bucket for issue #198.
  aws/create/bucket/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#305 Update the README AWS clean bucket for issue #197.
  aws/clean/bucket/README.md
Labels: hacktoberfest-accepted

#298 Updated python3 template
  templates/create_formula/languages/python3/config.json
  templates/create_formula/languages/python3/src/formula/formula.py
  templates/create_formula/languages/python3/src/main.py
Labels: hacktoberfest-accepted

#307 Update the README AWS delete bucket for issue #199.
  aws/delete/bucket/README.md
Labels: hacktoberfest-accepted

#306 Some fixes to initial python3 formula creation
  templates/create_formula/languages/python3/src/formula/__init__.py
  templates/create_formula/languages/python3/src/formula/formula.py
  templates/create_formula/languages/python3/src/main.py
  templates/create_formula/languages/python3/src/requirements.txt
Labels: hacktoberfest-accepted

#310 Readme - rit kafka list topic
  kafka/list/topic/README.md
Labels: Hacktoberfest

#309 Readme - rit kafka create topic
  kafka/create/topic/README.md
Labels: Hacktoberfest, hacktoberfest-accepted
