Repository ZupIT/ritchie-formulas, pull requests merged in 2020-11, with the labels that each got.

#312 Update RIT BEAGLE GENERATE SCAFFOLD formula README #204
  beagle/generate/scaffold/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#313 Docs improvement
  gitlab/publish/repo/README.md
  gitlab/publish/repo/doc/gif.gif
Labels: hacktoberfest-accepted

#311 Update the README KAFKA create topic for issue #221.
  kafka/create/topic/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#324 Fix/Github publish formula "branch"
  github/publish/repo/src/unix/formula/formula.sh
Labels: WIP, enhancement
